version: 2
updates:
# Fetch and update latest `composer` packages
- package-ecosystem: composer
  directory: '/'
  schedule:
    interval: daily
    time: '00:00'
  open-pull-requests-limit: 10
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope
# Fetch and update latest `github-actions` packages
- package-ecosystem: github-actions
  directory: '/'
  schedule:
    interval: weekly
    time: '00:00'
  open-pull-requests-limit: 10
  reviewers:
    - emaia
  assignees:
    - emaia
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope