name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [8.2, 8.3, 8.4]
        laravel: [12.*]
        dependency-versions: [prefer-stable]
        include:
          - laravel: 12.*
            testbench: 10.*
        exclude:
          - php: 8.4
            laravel: 12.*

          - php: 8.3
            laravel: 12.*

          - php: 8.2
            laravel: 12.*

    name: PHP ${{ matrix.php }} / Laravel ${{ matrix.laravel }} / ${{ matrix.dependency-versions }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
          tools: composer:v2
          coverage: none

      - name: Get composer cache directory
        run: echo "COMPOSER_CACHE_DIR=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
        id: composer_cache

      - name: Cache composer dependencies
        uses: actions/cache@v3.3.2
        with:
          path: ${{ steps.composer_cache.outputs.COMPOSER_CACHE_DIR }}
          key: dependencies-laravel-${{ matrix.laravel }}-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}
          restore-keys: dependencies-laravel-${{ matrix.laravel }}-php-${{ matrix.php }}-composer-

      - name: Install Composer dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" --no-interaction --no-update --dev
          composer update --${{ matrix.dependency-versions }} --prefer-dist --no-interaction --no-suggest

      - name: Run tests
        run: vendor/bin/pest
